language: node_js
sudo: required
dist: trusty
before_install:
  - cd /tmp
  - curl -s https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz > emsdk-portable.tar.gz
  - tar --extract --file emsdk-portable.tar.gz
  - python ./emsdk_portable/emsdk update
  - python ./emsdk_portable/emsdk install latest
  - python ./emsdk_portable/emsdk activate latest
  - sudo python ./emsdk_portable/emsdk activate latest --global
node_js:
  - "4"
  - "10"
